<% Settings.solr.url || raise("Settings.solr failed to initialize") %>

default: &default
  adapter: solr
  url: <%= Settings.solr.url %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

