<%
  solr_config = YAML.load(ERB.new(IO.read(Rails.root + 'config' + 'solr.yml')).result)[Rails.env].with_indifferent_access
%>

default: &default
  adapter: solr
  url: <%= solr_config["url"] %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

