# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTINGS__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: false
  default_host: # "%{tenant}.dev"
  admin_host:
  admin_only_tenant_creation: true

ssl_configured: false

action_controller:
  asset_host:

redis:
  default_namespace: hyku

<%
  # Read the config/solr.yml
  # - note that it specifies a URL that includes the collection path, which is stripped below.
  solr_config = YAML.load(ERB.new(IO.read(Rails.root + 'config' + 'solr.yml')).result)[Rails.env].with_indifferent_access
%>

solr:
  url:  <%= solr_config["url"].gsub(/solr\/.*/, 'solr/') %>
  configset: hyku
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: hyku
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

zookeeper:
  connection_str: "localhost:9983/configs"

active_job:
  queue_adapter: :async

active_job_queue:
  url:

s3:
  upload_bucket:

fits_path: "fits.sh"

google_analytics_id:

# Register here: http://www.geonames.org/manageaccount
geonames_username: 'jcoyne'

# The address to which the contact form is submitted
contact_email: ""

devise:
  account_signup: true
  # The address from which user invitations are sent
  invitation_from_email: "change-me-in-hyku-settings@example.org"
