# This is a sample config file that points to a solr server for each environment
<% Settings.solr.url || raise("Settings.solr failed to initialize") %>

default: &default
  url: <%= Settings.solr.url %>
  collection:
    dir: <%= Settings.solr.configset_source_path %>
    name: <%= Settings.solr.configset %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
