multitenancy:
  enabled: true

<%
  solr_namespace = 'hydra-test'
  solr_port = ENV.fetch('SOLR_TEST_PORT', 8985)
  solr_url = ENV.fetch('SOLR_URL', "http://127.0.0.1:#{solr_port}/solr/#{solr_namespace}/")
%>

solr:
  port: <%= solr_port %>
  url:  <%= solr_url %>
  collection:
    name: <%= solr_namespace %>

solr_wrapper:
  verbose: false
  port: <%= solr_port %>

zookeeper:
  connection_str: 'localhost:9985/configs'

